### ISSUE TITLE
lambda-radiko / ラジオNIKKEIの番組を指定するとエラー

### ISSUE THREAD

**Issue by egamasa** [egamasa/aws-scripts#1]
## 概要

`RadikoProgramFunction` へのダウンロードリクエスト時、ラジオNIKKEIの番組を指定すると `undefined method 'gsub' for nil` エラーが発生する。

## 再現手順

`RadikoProgramFunction` へ下記イベントを送信

```
{
  "title": "Anime & Seiyu Music Night",
  "station_id": "RN1",
  "week": "mon",
  "target": "title",
  "keyword": "Anime & Seiyu Music Night"
}
```

エラー

```
{
    "errorMessage": "undefined method `gsub' for nil",
    "errorType": "Function<NoMethodError>",
    "stackTrace": [
        "/var/task/app.rb:22:in `remove_html_tags'",
        "/var/task/app.rb:75:in `block in search_programs'",
        "/var/task/app.rb:63:in `map'",
        "/var/task/app.rb:63:in `search_programs'",
        "/var/task/app.rb:101:in `main'",
        "/var/task/app.rb:132:in `lambda_handler'",
        "/var/runtime/gems/aws_lambda_ric-3.0.0/lib/aws_lambda_ric/lambda_handler.rb:28:in `call_handler'",
        "/var/runtime/gems/aws_lambda_ric-3.0.0/lib/aws_lambda_ric.rb:88:in `run_user_code'",
        "/var/runtime/gems/aws_lambda_ric-3.0.0/lib/aws_lambda_ric.rb:66:in `start_runtime_loop'",
        "/var/runtime/gems/aws_lambda_ric-3.0.0/lib/aws_lambda_ric.rb:49:in `run'",
        "/var/runtime/gems/aws_lambda_ric-3.0.0/lib/aws_lambda_ric.rb:221:in `bootstrap_handler'",
        "/var/runtime/gems/aws_lambda_ric-3.0.0/lib/aws_lambda_ric.rb:203:in `start'",
        "/var/runtime/index.rb:4:in `<main>'"
    ]
}
```

**Comment by egamasa** [comment]
エラー発生個所

```
comment: remove_html_tags(program.elements['info']&.text),

def remove_html_tags(text)
  text.gsub(%r{</?[^>]+?>}, '').gsub(/\s+/, ' ').strip
end
```

ラジオNIKKEIの番組情報は info が空になっている

```
<prog id="10673647" master_id="" ft="20241021200000" to="20241021202000" ftl="2000" tol="2020" dur="1200">
  <title>Anime & Seiyu Music Night</title>
  <url>https://www.radionikkei.jp/musicnight/</url>
  ...
  <tsplus_out_ng>0</tsplus_out_ng>
  <desc>アニメの主題歌・挿入歌やサントラ、キャラソン、声優アーティストの楽曲から、毎週1アーティストごと、1作品ごと、あるいはテーマごとにピックアップし、ノンストップでお届けします。<br> 番組の終わりには、アニソンDJの中村瞳子（なかむらとうこ）さんが、お気に入りのナンバーを毎月1曲ご紹介します。<br> <br> そして毎月第3月曜日は、中村瞳子さんによるDJMixを20分めいっぱいお届けします！<br> <br> 番組X（旧twitter）アカウント：<a href="https://twitter.com/rnmusicnight">https://twitter.com/rnmusicnight</a><br> ハッシュタグは「#rn_asmn」です。</desc>
  <info/>
  <pfm/>
  ...
</prog>
```

nil セーフなコードに変更し、desc からも番組情報を取得するよう変更する。
